//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/29/2023 5:04:08 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace FelControl
{
    public partial class User {

        public User()
        {
            this.UserAdresses = new List<UserAdress>();
            this.UserServices = new List<UserService>();
            OnCreated();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public string LastName { get; set; }

        public int? TazId { get; set; }

        public decimal HourValue { get; set; }

        public virtual IList<UserAdress> UserAdresses { get; set; }

        public virtual IList<UserService> UserServices { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
