//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/29/2023 5:04:08 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace FelControl
{
    public partial class Client {

        public Client()
        {
            this.Phones = new Phones();
            this.ClientAdresses = new List<ClientAdress>();
            this.Services = new List<Service>();
            OnCreated();
        }

        public int Id { get; set; }

        [System.ComponentModel.DisplayName("First Name")]
        public string Name { get; set; }

        [System.ComponentModel.DisplayName("Last Name")]
        public string LastName { get; set; }

        [System.ComponentModel.DisplayName("Phones")]
        public Phones Phones { get; set; }

        public virtual IList<ClientAdress> ClientAdresses { get; set; }

        public virtual IList<Service> Services { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
