//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/29/2023 5:04:08 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace FelControl
{
    public partial class Service {

        public Service()
        {
            this.ContractService = new Contract();
            this.UserServices = new List<UserService>();
            this.ServiceAdresses = new List<ServiceAdress>();
            OnCreated();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string ImagenPrincipal { get; set; }

        public decimal Price { get; set; }

        public Contract ContractService { get; set; }

        public int ClientId { get; set; }

        public virtual IList<UserService> UserServices { get; set; }

        public virtual Client Client { get; set; }

        public virtual IList<ServiceAdress> ServiceAdresses { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
