//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/29/2023 5:04:08 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace FelControl
{
    public partial class UserService {

        public UserService()
        {
            this.Schedules = new List<Schedule>();
            OnCreated();
        }

        public int ServiceId { get; set; }

        public int UserId { get; set; }

        public virtual Service Service { get; set; }

        public virtual User User { get; set; }

        public virtual IList<Schedule> Schedules { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          UserService toCompare = obj as UserService;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.ServiceId, toCompare.ServiceId))
            return false;
          if (!Object.Equals(this.UserId, toCompare.UserId))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + ServiceId.GetHashCode();
          hashCode = (hashCode * 7) + UserId.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
