//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 7/29/2023 5:04:09 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace FelControl
{
    public partial interface IRepository<T>
    {
        System.Linq.IQueryable<T> All();
        void Add(T entity);
        void Remove(T entity);
    }
}
